site_name: "1С Conferences"
site_description: "Самые интересные конференции и митапы по 1С"
site_url: https://untru.github.io/1c-conferences/
site_author: "1С Community"

theme:
  name: material
  language: ru
  
  # Цветовая схема
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Авто
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Светлая
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Темная

  # Настройки темы
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.delay
    - navigation.instant.loading
    - navigation.instant.progress
    - navigation.instant.types
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  # Иконки
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  # Логотип
  logo: assets/logo.svg

  # Дополнительные настройки
  font:
    text: Roboto
    code: Roboto Mono

  # Социальные сети
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/untru/1c-conferences

# Плагины
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

# Навигация
nav:
  - Главная: index.md
  - Конференции:
      - "2025": events/2025/index.md
      - "Конференция 1С:Предприятие 8.3 - Москва": events/2025/2025-09-12-moscow.md
      - "Конференция 1С:Предприятие 8.3 - МО": events/2025/2025-09-13-moscow.md
  - О проекте: about.md

# Дополнительные настройки 
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/untru/1c-conferences
    - icon: fontawesome/brands/telegram
      link: https://t.me/1c_conferences
    - icon: fontawesome/brands/vk
      link: https://vk.com/1c_conferences
