name: 🗂️ Проверка навигации

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'docs/events/**/*.md'
      - 'docs/events/**/index.md'
      - '.github/workflows/auto-nav.yml'
      - 'generate_nav.py'
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  check-navigation:
    name: 🔍 Проверить навигацию
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Загрузить код
        uses: actions/checkout@v4

      - name: 🐍 Настроить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🗂️ Сгенерировать навигацию
        run: |
          python generate_nav.py

      - name: 🔍 Проверить изменения
        id: check-changes
        run: |
          if [ -n "$(git status --porcelain mkdocs.yml)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "📝 Навигация требует обновления"
            echo "🔍 Изменения:"
            git diff mkdocs.yml
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "✅ Навигация актуальна"
          fi

      - name: 💬 Комментарий в PR
        if: steps.check-changes.outputs.changes == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🗂️ **Навигация будет автоматически обновлена** при мерже этого PR!\n\n✨ Новые события будут добавлены в навигацию сайта.'
            })

      - name: ✅ Завершено
        run: |
          echo "🎉 Проверка навигации завершена!"
          if [ "${{ steps.check-changes.outputs.changes }}" == "true" ]; then
            echo "📝 Навигация будет обновлена при деплое"
          else
            echo "✅ Навигация уже актуальна"
          fi
