name: 🗂️ Автоматическое обновление навигации

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/events/**/*.md'
      - 'docs/events/**/index.md'
      - '.github/workflows/auto-nav.yml'
      - 'generate_nav.py'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'docs/events/**/*.md'
      - 'docs/events/**/index.md'
      - '.github/workflows/auto-nav.yml'
      - 'generate_nav.py'
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  update-navigation:
    name: 🔄 Обновить навигацию
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Загрузить код
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 🐍 Настроить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🗂️ Сгенерировать навигацию
        run: |
          python generate_nav.py

      - name: 🔍 Проверить изменения
        id: check-changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "📝 Обнаружены изменения в навигации"
            git status
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "✅ Изменений в навигации не обнаружено"
          fi

      - name: 📝 Зафиксировать изменения
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add mkdocs.yml
          git commit -m "🗂️ Автоматическое обновление навигации [skip ci]"
          git push

      - name: ✅ Завершено
        run: |
          echo "🎉 Навигация успешно обновлена!"
          echo "📋 Файлы изменены:"
          git diff --name-only HEAD~1 HEAD || echo "Нет изменений"
