name: 🚀 Сборка и деплой сайта

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  update-navigation:
    name: 🗂️ Обновить навигацию
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Загрузить код
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 🐍 Настроить Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🗂️ Сгенерировать навигацию
        run: |
          python generate_nav.py

      - name: 🔍 Проверить изменения навигации
        id: check-nav-changes
        run: |
          if [ -n "$(git status --porcelain mkdocs.yml)" ]; then
            echo "nav_changed=true" >> $GITHUB_OUTPUT
            echo "📝 Обнаружены изменения в навигации"
            git diff mkdocs.yml
          else
            echo "nav_changed=false" >> $GITHUB_OUTPUT
            echo "✅ Изменений в навигации не обнаружено"
          fi

      - name: 📝 Зафиксировать изменения навигации
        if: steps.check-nav-changes.outputs.nav_changed == 'true' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add mkdocs.yml
          git commit -m "🗂️ Автоматическое обновление навигации [skip ci]"
          git push

  build:
    name: 🔨 Собрать сайт
    runs-on: ubuntu-latest
    needs: update-navigation
    
    steps:
      - name: 📥 Загрузить код
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: 🐍 Настроить Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🗂️ Обновить навигацию (финальная проверка)
        run: |
          python generate_nav.py

      - name: 🔨 Собрать документацию
        run: |
          mkdocs build

      - name: 📦 Загрузить артефакт
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/

  deploy:
    name: 🚀 Деплой на GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: 📥 Загрузить код
        uses: actions/checkout@v4

      - name: 📥 Загрузить собранный сайт
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site/

      - name: 🚀 Деплой на GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
          commit_message: "🚀 Автоматический деплой сайта [skip ci]"